import {
  Bell,
  BellOff,
  BellRing,
  Bookmark,
  BookmarkCheck,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  Copy,
  CreditCard,
  Download,
  FilePenLine,
  Heart,
  HeartOff,
  LayoutGrid,
  List,
  ListOrdered,
  LoaderCircle,
  Maximize,
  Maximize2,
  Menu,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  Package,
  PackageCheck,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Play,
  RefreshCw,
  Repeat,
  Repeat2,
  RotateCcw,
  Save,
  Send,
  SendHorizontal,
  ShoppingCart,
  Shuffle,
  Trash2,
  Upload,
  Video,
  VideoOff,
  Volume2,
  VolumeX,
  X,
  type LucideIcon,
} from "lucide-react";
export const lucideIconMap = {
  bell: Bell,
  "bell-off": BellOff,
  "bell-ring": BellRing,
  bookmark: Bookmark,
  "bookmark-check": BookmarkCheck,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-down-up": ChevronsDownUp,
  "chevrons-up-down": ChevronsUpDown,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  copy: Copy,
  "credit-card": CreditCard,
  download: Download,
  "file-pen-line": FilePenLine,
  heart: Heart,
  "heart-off": HeartOff,
  "layout-grid": LayoutGrid,
  list: List,
  "list-ordered": ListOrdered,
  "loader-circle": LoaderCircle,
  maximize: Maximize,
  "maximize-2": Maximize2,
  menu: Menu,
  mic: Mic,
  "mic-off": MicOff,
  minimize: Minimize,
  "minimize-2": Minimize2,
  package: Package,
  "package-check": PackageCheck,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  pause: Pause,
  play: Play,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  "repeat-2": Repeat2,
  "rotate-ccw": RotateCcw,
  save: Save,
  send: Send,
  "send-horizontal": SendHorizontal,
  "shopping-cart": ShoppingCart,
  shuffle: Shuffle,
  "trash-2": Trash2,
  upload: Upload,
  video: Video,
  "video-off": VideoOff,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  x: X,
} satisfies Record<string, LucideIcon>;
export type LucideIconName = keyof typeof lucideIconMap;
