import {
  Archive,
  ArrowDown,
  ArrowUp,
  Bell,
  BellOff,
  BellRing,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  Bold,
  Bookmark,
  BookmarkCheck,
  Cable,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleSlash,
  Cloud,
  CloudRain,
  Contrast,
  Copy,
  CreditCard,
  Download,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  FileLock,
  FilePenLine,
  FileText,
  FileUser,
  Folder,
  FolderLock,
  FolderOpen,
  Heart,
  HeartOff,
  Italic,
  LayoutGrid,
  Link,
  List,
  ListOrdered,
  LoaderCircle,
  Lock,
  LockOpen,
  Maximize,
  Maximize2,
  Menu,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MousePointer2,
  Package,
  PackageCheck,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Pencil,
  Pin,
  PinOff,
  Play,
  RefreshCw,
  Repeat,
  Repeat2,
  RotateCcw,
  Save,
  Send,
  SendHorizontal,
  Shield,
  ShieldBan,
  ShieldCheck,
  ShoppingCart,
  Shuffle,
  SignalHigh,
  SignalLow,
  SignalZero,
  Snowflake,
  Sun,
  SunDim,
  SunMedium,
  Sunrise,
  Sunset,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignJustify,
  TextAlignStart,
  Thermometer,
  ThermometerSun,
  Trash2,
  Type,
  Unlink,
  Unplug,
  Upload,
  UserRound,
  UserRoundCheck,
  UserRoundX,
  Video,
  VideoOff,
  Volume2,
  VolumeX,
  WifiHigh,
  WifiLow,
  WifiOff,
  X,
  type LucideIcon,
} from "lucide-react";
export const lucideIconMap = {
  archive: Archive,
  "arrow-down": ArrowDown,
  "arrow-up": ArrowUp,
  bell: Bell,
  "bell-off": BellOff,
  "bell-ring": BellRing,
  bluetooth: Bluetooth,
  "bluetooth-connected": BluetoothConnected,
  "bluetooth-off": BluetoothOff,
  bold: Bold,
  bookmark: Bookmark,
  "bookmark-check": BookmarkCheck,
  cable: Cable,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-down-up": ChevronsDownUp,
  "chevrons-up-down": ChevronsUpDown,
  circle: Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dashed": CircleDashed,
  "circle-dot": CircleDot,
  "circle-slash": CircleSlash,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  contrast: Contrast,
  copy: Copy,
  "credit-card": CreditCard,
  download: Download,
  eraser: Eraser,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  "file-lock": FileLock,
  "file-pen-line": FilePenLine,
  "file-text": FileText,
  "file-user": FileUser,
  folder: Folder,
  "folder-lock": FolderLock,
  "folder-open": FolderOpen,
  heart: Heart,
  "heart-off": HeartOff,
  italic: Italic,
  "layout-grid": LayoutGrid,
  link: Link,
  list: List,
  "list-ordered": ListOrdered,
  "loader-circle": LoaderCircle,
  lock: Lock,
  "lock-open": LockOpen,
  maximize: Maximize,
  "maximize-2": Maximize2,
  menu: Menu,
  mic: Mic,
  "mic-off": MicOff,
  minimize: Minimize,
  "minimize-2": Minimize2,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  "mouse-pointer-2": MousePointer2,
  package: Package,
  "package-check": PackageCheck,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  pause: Pause,
  pencil: Pencil,
  pin: Pin,
  "pin-off": PinOff,
  play: Play,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  "repeat-2": Repeat2,
  "rotate-ccw": RotateCcw,
  save: Save,
  send: Send,
  "send-horizontal": SendHorizontal,
  shield: Shield,
  "shield-ban": ShieldBan,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  shuffle: Shuffle,
  "signal-high": SignalHigh,
  "signal-low": SignalLow,
  "signal-zero": SignalZero,
  snowflake: Snowflake,
  sun: Sun,
  "sun-dim": SunDim,
  "sun-medium": SunMedium,
  sunrise: Sunrise,
  sunset: Sunset,
  "text-align-center": TextAlignCenter,
  "text-align-end": TextAlignEnd,
  "text-align-justify": TextAlignJustify,
  "text-align-start": TextAlignStart,
  thermometer: Thermometer,
  "thermometer-sun": ThermometerSun,
  "trash-2": Trash2,
  type: Type,
  unlink: Unlink,
  unplug: Unplug,
  upload: Upload,
  "user-round": UserRound,
  "user-round-check": UserRoundCheck,
  "user-round-x": UserRoundX,
  video: Video,
  "video-off": VideoOff,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "wifi-high": WifiHigh,
  "wifi-low": WifiLow,
  "wifi-off": WifiOff,
  x: X,
} satisfies Record<string, LucideIcon>;
export type LucideIconName = keyof typeof lucideIconMap;
